name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud SDK
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      

      - name: Configure Docker
        run: |
          gcloud auth configure-docker "${{ secrets.CLOUD_RUN_REGION }}-docker.pkg.dev"

      - name: Build Docker image
        run: |
           docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image to Container Registry
        run: |
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }} --gcs-log-dir=gs://my-logs-bucket
          gcloud run deploy --image=gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }} --platform=managed --region=${{ secrets.CLOUD_RUN_REGION }} --allow-unauthenticated --quiet
